name: CI
on:
  push: { branches: [ master, main, feature/** ] }
  pull_request: { branches: [ master, main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - name: Install deps
        run: npm ci
      - name: Unit/Integration tests
        run: npm test -- --ci --reporters=default
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: E2E (Firefox + WebKit)
        run: npx playwright test --project=firefox --project=webkit --reporter=list
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: playwright-report, path: playwright-report, retention-days: 7 }